name: Check Issue Link in PR

on:
  pull_request:

jobs:
  check-issue-link:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR for Issue Link
        run: |
          PR_BODY=$(jq -r '.pull_request.body' "$GITHUB_EVENT_PATH")
          echo "$PR_BODY"
          if ! echo "$PR_BODY" | grep -qiE "#\\d+"; then
            echo "Error: PR description must include a linked Issue (e.g., 'resolve #123')."
            exit 1
          fi
