name: Check Issue Link in PR

on:
  pull_request:
    types: [opened, edited]

jobs:
  check-issue-link:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR for Issue Link
        run: |
          if ! grep -qiE "(close[sd]?|fix(ed|es)?|resolve[sd]?) #\\d+" "$GITHUB_EVENT_PATH"; then
            echo "Error: PR description must include a linked Issue (e.g., 'Closes #123')."
            exit 1
          fi
